set_property PACKAGE_PIN G25 [get_ports {HDMI_TX_P[2]}]
set_property PACKAGE_PIN H27 [get_ports {HDMI_TX_P[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_P[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_P[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_P[0]}]
set_property PACKAGE_PIN J26 [get_ports {HDMI_TX_P[0]}]
set_property PACKAGE_PIN AG11 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property PACKAGE_PIN E22 [get_ports clk_i_1]
set_property IOSTANDARD LVCMOS12 [get_ports clk_i_1]
set_property PACKAGE_PIN N24 [get_ports HDMI_CLK_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_CLK_P]
set_property PACKAGE_PIN AK30 [get_ports rstn_i]
set_property IOSTANDARD LVCMOS12 [get_ports rstn_i]
create_clock -period 10.000 -name clk_i [get_ports clk_i]
